### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zerobatu** [nibblebot/sublime-js2coffee#11]
I try to convert js to coffee with this plugin and the console show this error

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:113:29
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:120:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:156:4)
    at Module._compile (module.js:449:26)
    at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/js2coffee.coffee:13:36)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/js2coffee.coffee:1081:4)
    at Module._compile (module.js:449:26)
    at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/command.coffee:4:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/command.coffee:222:4)
    at Module._compile (module.js:449:26)
    at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/bin/js2coffee:10:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/bin/js2coffee:12:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:124:25)
    at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:166:29)
    at fs.stat.notSources.(anonymous function) (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:141:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

i have ubuntu with node -> coffee-script and js2coffee

**Comment by ghost** [comment]
+1 am also getting this

**Comment by ghost** [comment]
Seems it's a js2coffee issue

**Comment by ghost** [comment]
Solved at https://github.com/rstacruz/js2coffee/issues/189

**Comment by watkinshughes** [comment]
I see virtually the same error in OSX 10.7.5 with node -> coffee-script + js2coffee

**Comment by tachuris** [comment]
@zerobatu @propercursive See @michaelzibmz's workaround here: https://github.com/rstacruz/js2coffee/issues/189#issuecomment-14611812

**Comment by hsnmtw** [comment]
I received this error which is kind of simillar

<pre>
TypeError: Cannot read property 'length' of undefined
  at /usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:118:29
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:125:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/helpers.coffee:162:4)
  at Module._compile (module.js:449:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:179:19)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:362:17)
  at require (module.js:378:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/js2coffee.coffee:13:36)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/js2coffee.coffee:1127:4)
  at Module._compile (module.js:449:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:179:19)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:362:17)
  at require (module.js:378:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/command.coffee:4:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/lib/command.coffee:234:4)
  at Module._compile (module.js:449:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:179:19)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:362:17)
  at require (module.js:378:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/bin/js2coffee:7:1, <js>:10:3)
  at Object.<anonymous> (/usr/local/lib/node_modules/js2coffee/bin/js2coffee:12:4)
  at Module._compile (module.js:449:26)
</pre>
