### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by simonexmachina** [nibblebot/sublime-js2coffee#14]
This package is not listed in Package Control in Sublime Text 3. Is ST3 supported?

**Comment by andrewmartin** [comment]
I'm having issues getting it to work in ST3, and not seeing anything in the Console.

Any chance we could get this rolling for ST3? I love this package.

**Comment by andrewmartin** [comment]
Here's what I'm seeing now in ST3 Console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "/Users/andrewmartin/Library/Application Support/Sublime Text 3/Packages/JS2Coffee/JS2Coffee.py", line 13, in run
    output = self.js2coffee(contents)
  File "/Users/andrewmartin/Library/Application Support/Sublime Text 3/Packages/JS2Coffee/JS2Coffee.py", line 40, in js2coffee
    output, error = js2coffee.communicate(contents)
  File "X/subprocess.py", line 906, in communicate
  File "X/subprocess.py", line 1513, in _communicate
  File "X/subprocess.py", line 1608, in _communicate_with_poll
TypeError: 'str' does not support the buffer interface
```

**Comment by andrewmartin** [comment]
:+1: for this :smile: I keep swapping over to ST2 on a daily basis to do simple things like convert a Gruntfile.js over to Coffee. Would love to have this work in ST3 if possible! 

Thanks again for this awesome plugin.

**Comment by noctivityinc** [comment]
+1

**Comment by willhoag** [comment]
+1

**Comment by miketucker** [comment]
+1

**Comment by mdtjr** [comment]
- 1,000

If my python were up to the challenge, I'd put in the debugging time myself. The plugin is just so damn useful.

**Comment by liverbool** [comment]
+2

**Comment by berkaytheunicorn** [comment]
+1

**Comment by CurtisHumphrey** [comment]
+1

**Comment by TangMonk** [comment]
+1

**Comment by tsktsktsky** [comment]
+1

**Comment by kostasx** [comment]
The Sublime Text 3 version of the plugin can be found [here](https://github.com/aziz/sublime-js2coffee)

**Comment by voltechs** [comment]
For the record, to install the plugin @kostasx mentioned,

Command + Shift + P => Add Repository
enter the GitHub url... https://github.com/aziz/sublime-js2coffee
Then proceed to install it via package control.

BTW, I've made a PR to get this into the main package control repo: https://github.com/wbond/package_control_channel/pull/6041
